### ISSUE TITLE
unicode vulnerability?

### ISSUE THREAD

**Issue by attritionorg** [sindresorhus/internal-ip#11]
Hopefully this is the right 'internal-ip' package. Caught reference to a "unicode vulnerability" in this module via:
https://github.com/appcelerator/appc-pubsub/pull/9
https://github.com/appcelerator/appc-pubsub/pull/9/commits/0d28f05332bc6354e3ff533c4ac4fe6cc934146b

That project stopped using internal-ip due to the issue. Checking this repo, I don't see any indication of that and am wondering if this might be new to you, and/or if you were aware and there was more information available.

**Comment by silverwind** [comment]
I cannot see anything that would attribute to a 'unicode vulnerabilty', that's just too vague of a description. The module will be rewritten soon via https://github.com/sindresorhus/internal-ip/pull/9, so if there was something, it's likely gone by then.
