### ISSUE TITLE
Node.js 4 support

### ISSUE THREAD

**Issue by ai** [sindresorhus/internal-ip#12]
I understand that nobody likes to support old versions. But:

1. `webpack-dev-server` uses `internal-ip` (because this library is great)
2. All my open source libraries can be tested on Travis CI in Node.js 4. `yarn install` fail with engines check error.
3. Node.js 4 is still supported.

I check the sources and didn’t find critical parts for Node.js 6. Why we have engines limit in `package.json`?

@silverwind  Maybe we can add Node.js 4 support with 1-2 lines? If we need big work, of course, I will try to find some other solution.

**Comment by sindresorhus** [comment]
Node.js 4 is out of active LTS. Nobody is going to support it going forward. Just use an older version of this module if you need Node.js 4 support. It's targeting Node.js 6 as some of our dependencies targets Node.js 6.

**Comment by ai** [comment]
> Just use an older version of this module if you need Node.js 4 support.

I can’t :(. `webpack-dev-server` loads the latest version and it broke Travis CI.

> Node.js 4 is out of active LTS

Agree. But what is a reason why Node.js 4 can be supported?

**Comment by sindresorhus** [comment]
`Webpack-dev-server` has Node.js 4 as target in its package.json, so upgrading to the latest version of this module was a mistake on their part. You could get them to downgrade.

**Comment by ai** [comment]
Good point

**Comment by sindresorhus** [comment]
I want to target Node.js 6 in general as I want to use newer JS syntax like rest/spread/destructuring.

**Comment by ai** [comment]
BTW, you don’t have rest/spread/destructuring in this project (maybe I missed something?).

You added Node.js limit just because you have this limit in all other projects?

**Comment by silverwind** [comment]
I use destructuring and `Array.prototype.includes` in `default-gateway`, especially destructuring is pretty useful here:

https://github.com/silverwind/default-gateway/blob/5a724e2283fff9ed47f50c6b8122f2927e76928d/darwin.js#L19-L21

I wouldn't be opposed to a PR that makes it compatible with node 4, I guess, which would allow this module to drop to 4 too.

**Comment by silverwind** [comment]
node 4 compat done in https://github.com/silverwind/default-gateway/commit/d32ad95dbbfa0c2d7e2cf1db2985f2b01961c4e4 and released as default-gateway@2.2.2.

internal-ip also updated, internal-ip@2.0.3 is now node 4 compatible.

**Comment by ai** [comment]
Wow! Really fast. Thanks
