### ISSUE TITLE
sync methods still relevant

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/internal-ip#13]
This goes back a ways, but the changes to the API moving to an async, promise-based pattern in #9 are causing some headache with regard to updating. specifically, webpack-dev-server utilizes this module, and while a refactor to be more promise-friendly is in the works, it'll be some time before the project can use 2.x of internal-ip without a synchronous method. I'd like to suggest bringing back a synchronous method, even if it's not as accurate and contained a disclaimer, to allow use of the newer versions in apps/modules/projects that may not be able to leverage the updated async API as yet.

It would seem that @silverwind 's `default-gateway` module, and it's use of `execa`'s async patterns is the sole reason that the API is 100% async. It would be reasonable to provide sync methods via `default-gateway` if that module would also leverage [`execa.sync`](https://github.com/sindresorhus/execa#execasyncfile-arguments-options)

Of course, setting the dependency to the hard 1.2.0 version is always a solution. But providing synchronous methods here as well would be a big win.

**Comment by silverwind** [comment]
The old version before `default-gateway` was really inaccurate, it was basically guessing the interface to choose.

I guess I wouldn't be opposed to adding `defaultGateway.v{4,6}.sync` methods, but it'd be considerable rewrite and I'm not sure I have time for it right now.

**Comment by shellscape** [comment]
@silverwind check that PR 😉

**Comment by shellscape** [comment]
I've got a PR queued up for this issue, only waiting on `default-gateway` being published. (zero rush, sharing for posterity)

**Comment by silverwind** [comment]
default-gateway@2.6.0 is out.

**Comment by silverwind** [comment]
internal-ip@3.0.0 is out. In addition to the sync methods, it now returns `null` instead of loopback addresses on error.
