### ISSUE TITLE
Remove fallbacks to ::1 or 127.0.0.1

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/internal-ip#15]
I find the fallbacks to the localhost IPs don't really add any value and only complicate a user's code if they need a "real" IP. Should we remove them? It'd be a breaking change, but it's one I'm glad to take.

**Comment by sindresorhus** [comment]
What is the user expected to do/use then when `internal-ip` can't find the IP?

**Comment by silverwind** [comment]
I'd expect them to handle the thrown error depending on their use case. For some use cases, it might be appropriate to use the localhost addresses, but for others, a different action might be more fitting. I think it's not our responsibility to decide that.

**Comment by silverwind** [comment]
Simple example: You use `internal-ip` to retrieve the local ip on `server1` and communicate it to `server2`. For `server2`, the value of `127.0.0.1` would be outright wrong because it refers to their loopback address instead of the one on `server1`.

**Comment by sindresorhus** [comment]
Alright. I don't think it should throw though. It seems like it's an expected failure, and `null` would be more appropriate, I think. Our docs should mention when it could possibly return `null` and suggest how to handle it in different scenarios.

**Comment by silverwind** [comment]
Yeah, `null` seems reasonably here. I'll change this once https://github.com/sindresorhus/internal-ip/pull/14 has landed.
