### ISSUE TITLE
Don't skip IPv4 tests on Travis

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/internal-ip#22]
As of recent, Travis VMs now have IPv4 addresses (no IPv6 though), so IPv4 tests should no longer be skipped on Travis. I did a similar thing in https://github.com/silverwind/default-gateway/commit/4e66672b7aafd7cac75bfc8210882644f8344c7e.

**Comment by sindresorhus** [comment]
👍

**Comment by silverwind** [comment]
Depends on https://github.com/sindresorhus/internal-ip/issues/27.

**Comment by silverwind** [comment]
Actually, let's fold this into https://github.com/sindresorhus/internal-ip/issues/27.
