### ISSUE TITLE
AIX as OS support

### ISSUE THREAD

**Issue by rodiusd** [sindresorhus/internal-ip#23]
We are unable to install it on iSeries:

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for internal-ip@3.0.1: wanted {"os":"android,darwin,freebsd,linux,openbsd,sunos,win32","arch":"any"} (current: {"os":"aix","arch":"ppc64"})
npm ERR! notsup Valid OS:    android,darwin,freebsd,linux,openbsd,sunos,win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   aix
npm ERR! notsup Actual Arch: ppc64

Its a dependency for react.
Is there a way to support this os

**Comment by silverwind** [comment]
AIX support was recently added in 4.0.0 and this was already propagated to latest `webpack-dev-server`. Try updating all your dependencies, and check `npm ls internal-ip` to see where the upgrade is missing.
