### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/internal-ip#32]
At least the asynchronous part, in theory, should be possible.

Here's my browser implementation of [`internalIp.v4()`](https://gist.github.com/Richienb/737a0e30a3363478e4446f5f7fbcb5db).

**Comment by sindresorhus** [comment]
What's the use-case? The use-case is clear for servers, but in what situations would you need this in the browser?

**Comment by kl3sk** [comment]
For example, hide or show some website part for a specific IP (in a internal app).
This is a use case I want to implement.

**Comment by Richienb** [comment]
> What's the use-case?

Doing this sort of thing has gained traction in a StackOverflow question:

https://stackoverflow.com/q/20194722/8384910

**Comment by sindresorhus** [comment]
Alright. PR welcome.

**Comment by silverwind** [comment]
Wort mentioning, some software blocks this method as it's considered a privacy issue:

https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address
