### ISSUE TITLE
Not working on angular 8.3.20 on windows 10

### ISSUE THREAD

**Issue by rulfo71** [sindresorhus/internal-ip#34]
Hi there! 

I'm not getting this package to work on version 8.3.20 of angular, and windows 10. 
Let me know if you need any more information. 
I leave here the error, and my package.json, where you can see it does not compile.
![image](https://user-images.githubusercontent.com/5303411/92943321-03a1e700-f429-11ea-8961-ceb5dde8b47f.png)
[package.json.zip](https://github.com/sindresorhus/internal-ip/files/5209929/package.json.zip)

At last, how i am using it: 

![image](https://user-images.githubusercontent.com/5303411/92943526-4368ce80-f429-11ea-9f69-9cf5c2d9a019.png)
![image](https://user-images.githubusercontent.com/5303411/92943543-48c61900-f429-11ea-8ce7-5171e7672403.png)

I tried import internalIp from 'internal-ip' as one issue suggested, but it didn't work so I had to do import * as internalIp from 'internal-ip'

Thanks in advance!

**Comment by sindresorhus** [comment]
Your problem has nothing to do with this package specifically. Try asking on the Angular support channels.

**Comment by rulfo71** [comment]
Hello Sindre, thank you very much for your fast reply. 
I thought it would be something of this package, because if I comment the line "console.log(internalIp.v4.sync());", the application compiles. 
Perhaps i'm using incorrectly the package? 

Thank you very much again!
