### ISSUE TITLE
Need support commonjs！

### ISSUE THREAD

**Issue by SunSeekerX** [sindresorhus/internal-ip#40]
Using in nestjs project, only support commonjs.

nestjs project based on typescript, after build the module import by require.

**Comment by sindresorhus** [comment]
TS 4.5, which will be out soon, will support ESM. I have no plans to add back CommonJS support. I recommend just staying on the previous version.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
