### ISSUE TITLE
Issue with the node:os import.

### ISSUE THREAD

**Issue by thzero** [sindresorhus/internal-ip#41]
The following import statement does not actually seem to work.

import {networkInterfaces} from 'node:os';

Switching to

import {networkInterfaces} from 'os';

does.  Otherwise I get an ESM error.

Using node version v16.3.0 and npm version 7.15.1

**Comment by sindresorhus** [comment]
This sounds like a problem with your build tool or you're not actually on the Node.js version you are mentioning here. I would recommend trying to debug this yourself. This is not an issue with this package.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
