### ISSUE TITLE
Must use import to load ES Module: /usr/src/app/node_modules/internal-ip/index.js

### ISSUE THREAD

**Issue by leakhand** [sindresorhus/internal-ip#44]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/src/app/node_modules/internal-ip/index.js
backend      | require() of ES modules is not supported.
backend      | require() of /usr/src/app/node_modules/internal-ip/index.js from /usr/src/app/dist/presentation/interceptors/LoggingInterceptor.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
backend      | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/src/app/node_modules/internal-ip/package.json.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
